"""Add severity to event and mitre_id to alert

Revision ID: 96fd0af359ba
Revises: 2ff73e32e6b7
Create Date: 2026-07-08 14:21:47.211678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fd0af359ba'
down_revision: Union[str, None] = '2ff73e32e6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('mitre_id', sa.String(length=50), nullable=True))
    op.add_column('security_events', sa.Column('severity', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_events', 'severity')
    op.drop_column('alerts', 'mitre_id')
    # ### end Alembic commands ###
